### ISSUE TITLE
Call to undefined function Action_Scheduler\\Custom_Tables\\Migration\\wc_next_scheduled_action()

### ISSUE THREAD

**Issue by thenbrent** [Prospress/action-scheduler-custom-tables#30]
I'm seeing the following on after installing Custom Tables and running the migration on a staging copy of a live site:
```
PHP Fatal error: Uncaught Error: Call to undefined function Action_Scheduler\\Custom_Tables\\Migration\\wc_next_scheduled_action() in /wp-content/plugins/action-scheduler-custom-tables/src/Migration/Migration_Scheduler.php:59
Stack trace:
#0 /wp-content/plugins/action-scheduler-custom-tables/src/Plugin.php(79): Action_Scheduler\\Custom_Tables\\Migration\\Migration_Scheduler->is_migration_scheduled()
#1 [internal function]: Action_Scheduler\\Custom_Tables\\Plugin->schedule_migration()
#2 /wp-includes/class-wp-hook.php(284): call_user_func_array(Array, Array)
#3 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /wp-includes/load.php(679): do_action('shutdown')
#6 [internal function]: shutdown_action_hook()
#7 {main}
 thrown in /wp-content/plugins/action-scheduler-custom-tables/src/Migration/Migration_Scheduler.php on line 59
```

**Comment by JPry** [comment]
@thenbrent I've spent some time looking into this one to see about fixing it. Do you have any steps to reproduce? I've tried kicking off the migration manually via WP CLI, but that didn't trigger any errors.

It also appears that this shouldn't even be a problem in the first place, since it's trying to find a namespaced version of the function rather than the one in the global namespace.

If you have any more information, I'll be glad to keep looking.

**Comment by thenbrent** [comment]
@JPry no unfortunately, the only steps to really reproduce are something vague like "install ASCT, check error log". I noticed this showing up in the error log on one (or maybe two) of the sites I installed ASCT on pre-release. I haven't seen it locally, or on all sites. It also appeared only once, or very infrequently on those sites AFAICS (so it may related to first load or something).

It's not impacting functionality as far as I can tell. Migrations, regular usage all seem fine, so we can close this for now if you can't reproduce/see how it could happen.

**Comment by WPprodigy** [comment]
Not exactly the same, but I got the following after activating the master-branch version of this plugin on a site that hadn't been migrated yet:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Action_Scheduler\Custom_Tables\Migration\as_next_scheduled_action() in /wp-content/plugins/action-scheduler-custom-tables/src/Migration/Migration_Scheduler.php:59
Stack trace:
#0 /wp-content/plugins/action-scheduler-custom-tables/src/Plugin.php(83): Action_Scheduler\Custom_Tables\Migration\Migration_Scheduler->is_migration_scheduled()
#1 /wp-includes/class-wp-hook.php(284): Action_Scheduler\Custom_Tables\Plugin->schedule_migration()
#2 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /wp-includes/load.php(684): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /wp-content/plugins/action-scheduler-custom-tables/src/Migration/Migration_Scheduler.php on line 59
```

**Comment by thenbrent** [comment]
I had a closer look at this. I initially suspected the issue related to namespacing, because of the method included in the error: `Action_Scheduler\Custom_Tables\Migration\as_next_scheduled_action()`, and couldn't see how that would be the case.

However, I now suspect it's likely being logged when `'shutdown'` is called _before_ Action Scheduler has been loaded (and therefore, `as_next_scheduled_action()` is not available in `Action_Scheduler\Custom_Tables\Migration\Migration_Scheduler->is_migration_scheduled()`).

While that would be rare, it's certainly possible if code is terminating requests earlier than `'plugins_loaded'` with priority `1`, which is when AS is loaded. 

Fix incoming...

**Comment by WPprodigy** [comment]
Oh, nice find. That's definitely seems to be it, seeing that we had a separate fatal error on the site.
