### ISSUE TITLE
Fatal Error: Cannot call abstract method ActionScheduler_Logger::init() 

### ISSUE THREAD

**Issue by WPprodigy** [Prospress/action-scheduler-custom-tables#46]
I activated the master-branch version of this plugin on a test site that hadn't yet been migrated. This error was a nice surprise :)

Stack trace:

```
Fatal error: Uncaught Error: Cannot call abstract method ActionScheduler_Logger::init() in /wp-content/plugins/action-scheduler-custom-tables/src/DB_Logger.php:92
Stack trace:
#0 /wp-includes/class-wp-hook.php(284): Action_Scheduler\Custom_Tables\DB_Logger->init()
#1 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /wp-settings.php(467): do_action('init')
#4 /wp-config.php(11): require_once('/wp-set...')
#5 /wp-load.php(37): require_once('/wp-con...')
#6 /wp-admin/admin.php(31): require_once('/wp-loa...')
#7 /wp-admin/plugins.php(10): require_once('/wp-adm...')
#8 {main}
  thrown in /wp-content/plugins/action-scheduler-custom-tables/src/DB_Logger.php on line 92 
```

Introduced here: https://github.com/Prospress/action-scheduler-custom-tables/commit/b0fbfcd9e2394c78857aa76630d42a2eba8daea7. 

Resolved for now by using the tagged 1.0.0-beta version (probably should have done that to start).

**Comment by thenbrent** [comment]
@WPprodigy which version of Action Scheduler is active on the site?

`ActionScheduler_Logger::init()` isn't `Abstract` in 2.1.0 or newer. This commit changed that: https://github.com/Prospress/action-scheduler/commit/324e734e733a0d1326ed35895bacdce94d458cb0

2.1.0 and newer is the version included in WooCommerce core & Subscriptions (Action Scheduler will also load the newest version available in any plugin).

**Comment by thenbrent** [comment]
Ah right, yep that'll do it.

AS 2.1.0 only came to:

* WC 3.5.0 and
* Subscriptions 2.4.0

Thanks for the report on this. I'll add a dependency and notice to make sure AS 2.1.0 is communicated as a requirement.

To get v2.1.0, you can run Action Scheduler as a plugin if you can't update Subscriptions or WooCommerce just yet.

**Comment by thenbrent** [comment]
We already had dependency checks in `master`, but there was a bug. I've fixed that up in #47.

**Comment by rrennick** [comment]
@thenbrent is this one good to close?

**Comment by thenbrent** [comment]
@rrennick yep I think so now that the dependency check is working. 👍

**Comment by greguly** [comment]
Just an info for people who arrive here with this error on their sites.

https://woocommerce.com/products/follow-up-emails/ could be the culprit, disable it and error is gone.

**Comment by rrennick** [comment]
> disable it and error is gone.

Updating Follow Up Emails to the latest version would also work.
