### ISSUE TITLE
Plugin not initialized even when dependencies are met

### ISSUE THREAD

**Issue by gilliginsisland** [Prospress/action-scheduler-custom-tables#57]
There is an incorrect boolean check here

https://github.com/Prospress/action-scheduler-custom-tables/blob/d9a7a7a9a41af09b576613888ee2804bb1f69ea9/src/Plugin.php#L146-L150

Causing the plugin NOT to load when the dependencies ARE met.
The boolean logic needs to be reversed.
Currently when the deps are not met, the plugin will load, and when they are met, the plugin will not load, but will not display any notices because the deps are all met!

**Comment by rrennick** [comment]
The functionality of this plugin has been merged into the next version of Action Scheduler (3.0.0) which should be released to beta within a week https://github.com/Prospress/action-scheduler/tree/version_3_0_0 . This plugin is being deprecated.

**Comment by gilliginsisland** [comment]
That is great to hear.
I love the action scheduler project and am extremely excited for the custom tables to be built in!

**Comment by thenbrent** [comment]
@gilliginsisland we'd love some help beta test 3.0.0! It's by the far the largest release in AS's history. There's still one or two bugs to fix before we tag a beta, but as @rrennick said, we expect to tag a `3.0.0-beta-1` within a week.
