### ISSUE TITLE
$date from TimeZone_Helper not used?

### ISSUE THREAD

**Issue by igorbenic** [Prospress/action-scheduler-custom-tables#59]
Hi,

while working on a site using this tables, I found the code where the `ActionScheduler_TimezoneHelper::set_local_timezone` is used. The `$date` that is passed there seems not be used because the `set_local_timezone` (https://github.com/woocommerce/action-scheduler/blob/master/classes/abstracts/ActionScheduler_TimezoneHelper.php#L18-L32) does not pass `$date` by reference.

Wouldn't the `$date_gmt` and `$date_local` be the same here:
https://github.com/Prospress/action-scheduler-custom-tables/blob/master/src/DB_Logger.php#L28-L30 ?

Maybe I am wrong here, but just checking to see if I understand it correctly.

**Comment by rrennick** [comment]
> does not pass $date by reference.

As of PHP 5, by default objects are passed by reference https://www.php.net/manual/en/language.oop5.references.php

Also, this plugin is deprecated in favour of Action Scheduler 3.X which implements an enhanced version of this data store.

**Comment by igorbenic** [comment]
Thanks for the clarification and a fast response! Closing this then :D
