### ISSUE TITLE
Ready for new installs/activations

### ISSUE THREAD

**Issue by cbrcongit** [Prospress/action-scheduler-custom-tables#9]
Is this just a 'beta' in terms of migration/compatibility with existing active plugin users, 
or are there still unfinished/untested features that new installs need to worry about?

**Comment by thenbrent** [comment]
@cbrcongit I wouldn't install it anywhere yet. For best results it requires both a pre-release version of Action Scheduler, including an open PR on that repo, and ideally also then the code in PR #4 from this repo.

We will tag an RC once we have everything in place.
